sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: T9jspH340RHupoOgqOZNHho59oHSvWQyhiJKpRWGSUUImNLM3sTxIVlGB/3nHZddo3jHhR0m9jao2iv/fTDG604jdM7gfYqMYkyzLZdc94rpc0YIfBPLjbytBxHT8gh/B+BUIAomIPKI4Jyd/WS9WAzt5/U1f/lyOWdPMvv7oIK5AZmx7yOXahCme3lloYy/fzjmg++R5TfYNpjdx6KgZ/GepRTdaTrvy98GFm41yvkiwZHuiTy29OV63kfrDfqDfmbCFgGRGySSO45eNjnUz3ghYRkxKz2UzrGbaEp+f08eACCSlVWaywem2kgyo707dgV9Sm2wj12dsnTMaryTVpb6aX7dNpaGKBiUGQ6T+SUuF6MQypy60apCbgU6kCSgf+ckCRqlN+8M7VHKeO4yQOQlN3oaM1ijKsbo0F8DkxNyQ18InrmOAuUnnfxQSFs739QyjjKBIb50v2DXhtoeM5rppCgX8uHwhr+Ck0gkFufOzFMipBSvjVvV0f74jSERAMgdnxaiA9pIG44wbJ0MoBDemmBGLXue4rED97Tt7Cb8KVp94aAJ1eOkPjkwUekrXjDK4wjjIUK2Y6QXnR9N4Vs1AN679n1mEskAJLhO1IGk6d9cudouRebwofAWlzg5WqFTu9cV7dffkf+S64AAaZtaqnlGgjRiTNyxXn3WlDM=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Soul-of-Man-under-Socialism_1017
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy